### ISSUE TITLE
Needs documentation about playgrounds notebooks and building scripts.

### ISSUE THREAD

**Issue by sonsongithub** [sonsongithub/numsw#15]
Needs documents about ."How to build playgrounds notebooks" and "Which is the newest one?"

1. some old playgrounds is unnecessary?
2. which one is the newest notebook?
3. Should I run a script in order to build the newest notebook?

**Comment by omochi** [comment]
I write roughly here temporary.

- `playbook/Cat.playgroundbook` is unnecessary now. 
   But if i mistaken, some latest code is in it and its not recovered to sources now.
   Because we are directly edit book last time...

- to build latest ipad book, do this.

```
$ tool/build-ipad-playbook.rb
```

  this generate `playbook/numsw-ipad.playgroundbook`

- to build latest xcode playground

```
$ tool/build-xcode-playbook.rb
```

  this generate `playbook/numsw-xcode.playgroundbook`

- they are written in ruby 2.2.2

- `playbook/ipad` is book material.
- `playbook/xcode` is xcode playground material.

**Comment by sonsongithub** [comment]
OK.
I'll fix them later, at the other branch. Thank you.

**Comment by sonsongithub** [comment]
24fa10ee4c15b8963c91f6208f9eea4475b03922
